version: "3"
services:
  mini-server1:
      image: "php:apache"
      volumes: 
        - ./server:/var/www/html
  mini-server2:
      image: "php:apache"
      volumes: 
        - ./server:/var/www/html
  mini-server3:
      image: "php:apache"
      volumes: 
        - ./server:/var/www/html
  loadb:
    build: ./loadb
    ports: 
      - 9090:9090




